### ISSUE TITLE
11xx issues are not present

### ISSUE THREAD

**Issue by gschare** [cu-mkp/issue-tracker-archive#15] opened 2021-04-06 19:31 UTC
E.g. issue 1186 does not show up in the index of issues in the GitHub Pages site.
However, issue 1186 is present in both the `comments.json` and `issues.json`.

**Comment by gschare** [comment] 2021-04-06 19:33
The listing appears to jump from 1034 to 1207, and instead of 1209, there is 1566.

**Comment by gschare** [comment] 2021-04-06 19:45
One possible explanation is a series of IO errors that fail to be caught and properly handled.

**Comment by gschare** [comment] 2021-04-06 19:49
It is likely that the source of the problem is in `build.hs` because the issues are present in the JSON.

**Comment by njr2128** [comment] 2021-04-14 16:48
In the most recent build, this is no longer a problem. It seems to be fixed:
![image](https://user-images.githubusercontent.com/14779727/114748200-aa33ca80-9d1f-11eb-8ccf-6b00c9ddd860.png)

Unclear what the cause (or the fix) was. Closing

**Closed by njr2128** 2021-04-14 16:48 UTC
Labels: bug
